import { Abril_Fatface, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const abril_fatface = Abril_Fatface({
  variable: "--font-abril",
  subsets: ["latin"],
  weight: [ "400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${abril_fatface.variable} font-montserrat antialiased bg-background`}
      >
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
